# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Eliseo Gaston Lopez Ariza
title: Lead Site Reliability Engineer
# email: liseu.90@hotmail.com
# website: www.github.com/sproogen/resume-theme

darkmode: true

# plastic links
github_username:  eliseogaston
linkedin_username: eliseogaston
additional_links:
- title: Email me!
  icon: fa fa-envelope
  mailto: liseu.90@hotmail.com
#- title: Book Time with Me!
#  icon: fa fa-calendar
#  url: https://calendly.com/eliseogaston/book-me


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  I am a Lead Site Reliability Engineer with over 10 years of experience working with backend and cloud environments using technology stacks like .NET, Java and Go.
  I work with large and small teams to design, build, manage, monitor and architect micro-services and distributed HA systems that best meet the customer's requirements.
  
  My expertise in cloud infrastructure design architectures, strong skills in DevOps/DevSecOps, and years of experience in every part of the software development lifecycle help me make every decision professionally.
  
  I'm most interested in security, observability, and performances. Automating all of this is my fervent interest.
content:
  - title: Skills
    layout: text
    content: | 
          ![AWS](https://img.shields.io/badge/AWS-%23FF9900.svg?style=plastic&logo=amazon-aws&logoColor=white)
          ![Terraform](https://img.shields.io/badge/terraform-%235835CC.svg?style=plastic&logo=terraform&logoColor=white)
          ![Ansible](https://img.shields.io/badge/Ansible-black.svg?style=plastic&logo=ansible&logoColor=white&color=black)
          ![AWS EKS](https://img.shields.io/badge/EKS-white?style=plastic&logo=amazoneks)
          ![K8s](https://img.shields.io/badge/K8s-blue.svg?style=plastic&logo=kubernetes&logoColor=blue&color=white)
          ![ContainerD](https://img.shields.io/badge/ContainerD-white.svg?style=plastic&logo=containerd&logoColor=black&color=white)
          ![Docker](https://img.shields.io/badge/Docker-2496ED?style=plastic&logo=docker&logoColor=fff)
          
          ![FluentD](https://img.shields.io/badge/FluentD-black.svg?style=plastic&logo=fluentd&logoColor=blue&color=black)

          
          ![MongoDB](https://img.shields.io/badge/MongoDB-%234ea94b.svg?style=plastic&logo=mongodb&logoColor=white)
          ![CassandraDB]()
          ![Redis](https://img.shields.io/badge/redis-%23DD0031.svg?style=plastic&logo=redis&logoColor=white)
          ![PostgreSQL](https://img.shields.io/badge/PostgreSQL-white?style=plastic&logo=postgresql&logoColor=#4169E1)
          ![MS SQL Server]()
          ![Oracle PL/SQL]()
          ![AmazonDynamoDB](https://img.shields.io/badge/Amazon%20DynamoDB-4053D6?style=plastic&logo=Amazon%20DynamoDB&logoColor=white)
          ![MariaDB](https://img.shields.io/badge/MariaDB-003545?style=plastic&logo=mariadb&logoColor=white)
                
          ![Apache Kafka](https://img.shields.io/badge/Apache%20Kafka-000?style=plastic&logo=apachekafka)
          ![AWS SQS](https://img.shields.io/badge/AWS%20SQS-white?style=plastic&logo=amazonsqs)
          ![AWS EventBridge]()
                
          ![.Net](https://img.shields.io/badge/.NET-5C2D91?style=plastic&logo=.net&logoColor=white)
          ![Java](https://img.shields.io/badge/Java-grey?style=plastic&logo=openjdk)
          ![Go](https://img.shields.io/badge/go-%2300ADD8.svg?style=plastic&logo=go&logoColor=white)
                
          ![GitLab](https://img.shields.io/badge/GitLab-orange.svg?style=plastic&logo=GitLab&logoColor=white&color=orange)
          ![GitHub](https://img.shields.io/badge/GitHub-white.svg?style=plastic&logo=Github&logoColor=white&color=black)
          ![GitHub Actions](https://img.shields.io/badge/github%20actions-%232671E5.svg?style=plastic&logo=githubactions&logoColor=white)
          ![Jenkins](https://img.shields.io/badge/Jenkins-white?style=plastic&logo=jenkins&logoColor=#D24939)
          ![FluxCD]()
          ![Argo CD](https://img.shields.io/badge/Argo_CD-white.svg?style=plastic&logo=argo&logoColor=orange&color=white)
          ![Octopus Deploy](https://img.shields.io/badge/octopus%20deploy-0D80D8?style=plastic&logo=octopusdeploy&logoColor=white)
                
          ![Datadog](https://img.shields.io/badge/Datadog-white.svg?style=plastic&logo=datadog&logoColor=black&color=white)
          ![New Relic](https://img.shields.io/badge/New_Relic-black.svg?style=plastic&logo=new%20relic&logoColor=lightgreen&color=darkblue)
          ![Prometheus](https://img.shields.io/badge/Prometheus-white.svg?style=plastic&logo=prometheus&logoColor=orange&color=white)
          ![Grafana](https://img.shields.io/badge/Grafana-black.svg?style=plastic&logo=grafana&logoColor=black&color=orange)
          ![AWS Cloudwatch](https://img.shields.io/badge/AW%20CloudWatch-white?style=plastic&logo=amazoncloudwatch&logoColor=#FF4F8B)
          ![SigNoz]()
          
          ![Snyk](https://img.shields.io/badge/Snyk-4C4A73?logo=snyk&logoColor=fff)
          ![SonarQube](https://img.shields.io/badge/SonarQube-F3702A?logo=sonarqube&logoColor=fff)
          ![KUBEBENCH]()
          ![Trivy](https://img.shields.io/badge/Trivy-black?style=plastic&logo=trivy&logoColor=#1904DA)
          ![JFrog](https://img.shields.io/badge/JFrog-white?style=plastic&logo=jfrog&logoColor=#40BE46)

          ![JWT](https://img.shields.io/badge/JWT-black?style=plastic&logo=JSON%20web%20tokens)
          ![OKTA](https://img.shields.io/badge/OKTA-darkblue.svg?style=plastic&logo=okta&logoColor=white&color=darkblue)
          ![AUTH0](https://img.shields.io/badge/Auth0-black?style=plastic&logo=Auth0)
          ![KEYCLOAK](https://img.shields.io/badge/keycloak-green?style=plastic&logo=Keycloak)

          ![Jira](https://img.shields.io/badge/Jira-blue?style=plastic&logo=jira&logoColor=#0052CC)
          ![PagerDuty](https://img.shields.io/badge/PagerDuty-black?style=plastic&logo=pagerduty&logoColor=#06AC38)
          ![OpsGenie](https://img.shields.io/badge/OpsGenie-blue?style=plastic&logo=opsgenie&logoColor=#172B4D)

  - title: Experience
    layout: list
    content:
      - layout: left
        title: GlobalLogic 
        sub_title: Lead Platform Engineer
        caption: September 2023 - Present
        description: | 
              - Standarize more than 30 customer's teams development experience.
              - Coordinate and Lead Platform Team to provide Best Practices DevOps, DevSecOps, Cloud Architectures and Compliance as a standard
              - Design and architect high level distributed and complex HA systems
              - Review retrofeed and Customer feedback as improving metrics to track and plan work based on priorities and necesities.
              - Observe Infrastructure, Metrics and Budgets to give the customers the best cost efective solution for their business across all the teams.
              - Standarize metrics, strategies and incident management across many teams.

      - layout: left
        title: Invenco by GVR
        sub_title: Senior Platform Engineer
        caption: September 2022 - September 2023
        description: |
              - Improve Dev experience and business KPIs
              - Implement Internal Developer Portal for self serve services (backstage)
              - Centralize Enterprise Artifactory solution and workflows acorss all products, to match security, quality and performance.
              - Implement Reusable Terraform, Ansible and Go shared libraries for Teams to standarize application across products
              - Coordinated efficient large-scale continuos delivery for IoT, Healthcare and PCI environments, witch involves more than 30 products.
              - Design and automate self-healing systems using Kubernetes operators and Incident runbooks
              - Design, Manage and Admin Incident Management System, Implement Alerting Systems (PagerDuty, Prometheus, AWS Cloudwatch, Icinga)
              - Design, Implement and Review SLAs, SLOs at Enterprise Level to match on each product the same quality
      
      - layout: left
        title: Marqeta
        sub_title: Lead Site Reliability Engineer
        caption: December 2021 - August 2022
        description: |
              - Implement CI/CD pipelines to automate software development lifecycle
              - Implement OCTA worflows for users creation, authentication and authorizations
              - Create, Mantain and Architect AWS LAMBDA for provitioning of accounts and services
              - Implement Observability and Monitoring on Serverless architecture
              - Reveal and Retrofit business needs for tracking business value. 
        
      - layout: left
        title: Leonardo247
        sub_title: Lead Site Reliability Engineer
        caption: February 2021 - December 2021
        description: | 
              - Skilled at working independently and collaboratively in a team environment.
              - Design new infrastructure on AWS EKS,
              - Infrastructure as Code using Terraform and Ansible.
              - Design security and scalability for development team to access resources.
              - Implement, Design and Review SOC 2 security compliance
              - DevSecOps practices using DAST and SAST software on GitLab Pipelines.
              - Design and monitoring SDLC and Infrastructure with Prometheus and Grafana and Datadog
                
      - layout: left
        title: Becton & Dickinson 
        sub_title: Senior Site Reliability Engineer
        caption: December 2019 - January 2021
        description: |
              - Observe, Analyze and Review Infrastructure and Application for cost effective solutions. 
              - Containarize applications using Docker and Kubernetes for modernization and Continous Delivery on Github Actions
              - Design, Create and Implement 3-parties integrations with platform. (AWS Athena, AWS EMR, AWS QUICKSIGHTS)
              - Monitoring, Design and Review transactional databases health and performance (PL-SQL and Postgres)
              - Redesign DB schemas and operations through distributed events for better performance no NO-SQL database (MongoDB and DyanamoDB)
              - Create and Mantain Infrastructure cost, monitoring and solutions using Datadog and AWS Cloudwatch
              - Design, Implement and Maintain Auth0 workflows for authentication and authorization across all Products through SSO/OIDC
                
      - layout: left
        title: Walkers
        sub_title: Lead Software Engineer
        caption: August 2018 - December 2019
        description: | 
              - Migration of old .NET 2 and ASP applications to .NET CORE and Web Technologies
              - Design, Create and Implement a new Standalone frontend architecture using angular
              - Split into Microservices and background jobs old .NET monolithic to be used for frontend
              - Redesign DB schemas and operations through event hubs  
      
      - layout: left
        title: Coalfire
        sub_title: Senior Software Engineer (.NET and Java)
        caption: August 2016 - August 2018
        description: |
              - Cybersecurity. Healthcare, PCI DSS, FedRAMP, HIPPA
              - Design, Scale and Maintain HA Public API with .NET and Java, (Monolithics and Serverless APIs)
              - Retrieve business values and requirements from stackeholders and customers
              - Performance testing and monitoring for backend applications performance
              - Opeartate and Maintain Multi-schema MS SQL Server Cluster Database. Monitor and performance improvements on low-performant code
              - Design, Operate, Build and Scale Mongodb cluster onpremise for lower and Atlas for Production. Snapshoting and Versioning system design architecture-
              - Implement Event-driven architecture with Kafka, AWS SQS, AWS SNS
              - Migration from Monolith to distributed architecture using Kubernetes on AWS EKS, and event-sourcing systems such as Apache Kafka.

      - layout: left
        title: SanCor
        sub_title: .NET Software Engineer
        caption: August 2015 - April 2016
        description: | 
              - Refresh old intranet site to a public hosted domain web application for insurance
              - Maintain, modernize and stabilize .NET ASP.NET application on IIS.
              - Maintain, patch and operate Servers for Database, IIS and FTP.
              - Design ServiceBus integration systems for high availability and reliability event-driven transactional environment
              - Analyse and Optimize DB operations for low timing responses across tenants
      
      - layout: left
        title: Plus Sistemas S.A
        sub_title: Java Software Engineer
        caption: May 2013 - July 2015
        description: | 
              - Troubleshot and resolved performance issues for databases and software.
              - Analyze, evaluate and develop new web and database applications.
              - Software Engineer on .NET stack using MVC, WebAPI, SQL, Razor and web technologies.
              - Responsible for Continuos Integration using TFS, WebDeploy, IIS and Jenkins
              - Monitored database performance to keep workflows running smoothly.

      - layout: left
        title: Ministerio Salud Provincia de Buenos Aires
        sub_title: Database Administrator
        caption: September 2011 - March 2013
        description: | 
              - Administering and monitoring databases by proactively resolving issues and onprem servers.
              - Develop and patch databases to perform best on customer's data.
              - Implement procedures and Hardening to prevent data loss and maximize system availability.
              - Process data integration and data resiliency and maintenance.
              - Maintain database designs, schemas and data models. 

  
  - title: Education
    layout: list
    content:
      - layout: left
        title: Universidad Nacional La Plata
        caption: 2009 - 2016
        sub_title: BSc Computer Science
        description: | 
            During my time at university I learnt most of my key skills that have I have taken through my career such as teamwork collaboration and working to tight deadlines on Agile environments.
            
            I owned a master in HA and Grid Scalable System Designs and Cloud Distributed Architectures.
            
            I had lot of experience at that time with Cloud and HA designs  

# Footer
footer_show_references: true
references_title: Contact Me!

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
