# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Eliseo Gaston Lopez Ariza
title: Senior Site Reliability Engineer
email: liseu.90@hotmail.com
# website: www.github.com/sproogen/resume-theme

darkmode: true

# plastic links
github_username:  eliseogaston
linkedin_username: eliseogastonlopezariza
additional_links:
- title: Book Time with Me!
  icon: fa fa-calendar
  url: https://calendly.com/eliseogaston/book-me

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  I am a Senior Site Reliability Engineer with more than +10 years of experience on Software Development using stacks like .NET, Java, Python and GoLang.
  As a Technical Lead & Solutions Architect, for small and big teams, I help them designing micro-services and complex HA systems that will fit the customers need.
  
  My proficiency on Cloud Infrastructure Design Architectures, strong skills on DevOps/DevSecOps but also many years involved on every part of the Software Development Lifecycle helps me design, plan and make technical resolutions very accurate and professionally.
  
  Passionate about security, performance , automation and observability.

content:
  - title: Skills
    layout: text
    content: | 
        **Cloud Providers**:  AWS, Azure, GCP, Openshift
            
        **Monitoring**:  Prometheus, Grafana, Loki, FluentD, FluentBit, Azure Application Insights
            
        **Observability**:  Datadog, New Relic, AWS CloudWatch

        **FinOps**: Terracost, Kubecost, CloudZero, Datadog, AWS Cost Management, Azure Cost Explorer
            
        **Containerization**:  Vagrant, Docker, COntainerD, LXC/LXD, BuildKit, Kaniko, Podman
        
        **Orquestation**:  Kubernetes, EKS, AKS, GKE, Docker Swarm, Docker Compose
        
        **Package Management**:  Helm, Kustomize
        
        **GitOps**:  ArgoCD, Tekton, Flux, Jenkins-x
        
        **VCS**:  Gitlab, Github, Azure DevOps
        
        **Infastructure as Code**:  Terraform, Pulumi, Crossplane, AWS CDK, Azure ARM Templates
        
        **Configuration as Code**:  Ansible, SaltStack
        
        **Programmin Languaje**:  NET, Java, Golang, Python
        
        **Databases**:  SQLs, MongoDB, Redis, Cassandra, DynamoDB
            
        **Methodologies**:  Git, Scrum, Kanban, SaFE

        **Shifts**: PagerDuty, AlertManager, Jira Incident Management Suite

  - title: Experience
    layout: list
    content:
      #- layout: left
      #  title: Svitla / Gilbarco Veeder-Root
      #  sub_title: Lead Platform Engineer
      #  caption: September 2023 - Present
      #  description: | 
      #          - Responsible for the health, cost and wellness of infrastructure across the world.
      #          - IaC and CaC through gitops principles using terraform, ansible and aws cdk
      #          - Github Workflows for CICD
      #          - Event System Architectures using Kafka and EventService Hub
      #          - AWS muti account & multi region control.
      #          - Review and mantain IoT microservices with high availability and low latency
      #          - Plan, Design and Implement business and development architecture needs with Cloud Ops High standards
                
      - layout: left
        title: GlobalLogic 
        sub_title: Lead Platform Engineer
        caption: January 2023 - Present
        description: | 
                - Lead of Platform Engineer Team which standarize more than 30+ customers' teams
                - Coordinate and Lead Platform Team to provide Best Practices DevOps, DevSecOps, Cloud Architectures and Compliance as a standard
                - Design and architect micro-services and complex systems
                - Follow requirements,metrics and feedback from customers to get that improvement area retrofit.
                - Coordinated efficient large-scale software deployments and architecture for IoT, Healthcare and PCI environments.
                - Observe Infrastructure, Metrics and Budgets to give the customers the best cost efective solution for their business.  
                        
                ![AWS](https://img.shields.io/badge/AWS-%23FF9900.svg?style=plastic&logo=amazon-aws&logoColor=white)
                ![Octopus Deploy](https://img.shields.io/badge/octopus%20deploy-0D80D8?style=plastic&logo=octopusdeploy&logoColor=white)
                ![GitHub Actions](https://img.shields.io/badge/github%20actions-%232671E5.svg?style=plastic&logo=githubactions&logoColor=white)
                ![GitLab CI](https://img.shields.io/badge/gitlab%20ci-%23181717.svg?style=plastic&logo=gitlab&logoColor=white)
                ![CircleCI](https://img.shields.io/badge/circle%20ci-%23161616.svg?style=plastic&logo=circleci&logoColor=white)
                ![MongoDB](https://img.shields.io/badge/MongoDB-%234ea94b.svg?style=plastic&logo=mongodb&logoColor=white)
                ![Redis](https://img.shields.io/badge/redis-%23DD0031.svg?style=plastic&logo=redis&logoColor=white)
                ![MySQL](https://img.shields.io/badge/mysql-%2300f.svg?style=plastic&logo=mysql&logoColor=white)
                ![MariaDB](https://img.shields.io/badge/MariaDB-003545?style=plastic&logo=mariadb&logoColor=white)
                ![ApacheCassandra](https://img.shields.io/badge/cassandra-%231287B1.svg?style=plastic&logo=apache-cassandra&logoColor=white)
                ![AmazonDynamoDB](https://img.shields.io/badge/Amazon%20DynamoDB-4053D6?style=plastic&logo=Amazon%20DynamoDB&logoColor=white)
                ![Neo4J](https://img.shields.io/badge/Neo4j-008CC1?style=plastic&logo=neo4j&logoColor=white)
                ![Apache Kafka](https://img.shields.io/badge/Apache%20Kafka-000?style=plastic&logo=apachekafka)
                ![.Net](https://img.shields.io/badge/.NET-5C2D91?style=plastic&logo=.net&logoColor=white)
                ![JWT](https://img.shields.io/badge/JWT-black?style=plastic&logo=JSON%20web%20tokens)
                ![RabbitMQ](https://img.shields.io/badge/Rabbitmq-FF6600?style=plastic&logo=rabbitmq&logoColor=white)
                ![Azure](https://img.shields.io/badge/azure-%230072C6.svg?style=plastic&logo=microsoftazure&logoColor=white)
                ![Google Cloud](https://img.shields.io/badge/GoogleCloud-%234285F4.svg?style=plastic&logo=google-cloud&logoColor=white)
                ![Neovim](https://img.shields.io/badge/NeoVim-%2357A143.svg?&style=plastic&logo=neovim&logoColor=white)
                ![Go](https://img.shields.io/badge/go-%2300ADD8.svg?style=plastic&logo=go&logoColor=white)
                ![Terraform](https://img.shields.io/badge/terraform-%235835CC.svg?style=plastic&logo=terraform&logoColor=white)

      
      - layout: left
        title: Taller Technologies / Marqeta
        sub_title: Senior Staff Engineer
        caption: April 2022 - December 2022
        description: |
                - Implement CI/CD pipelines to automate provisioning of accounts
                - Implement OCTA worflows for users creation provition
                - Create, Mantain and Architect AWS LAMBDA for provitioning of accounts and services
                - Implement Observability and Monitoring on Serverless architecture
                - Reveal and Retrofit business needs for tracking business value.  

                ![AWS](https://img.shields.io/badge/AWS-%23FF9900.svg?style=plastic&logo=amazon-aws&logoColor=white)
                ![OKTA](https://img.shields.io/badge/OKTA-%23FF9900.svg?style=plastic&logo=okta&logoColor=white)
                ![awslmabdas](https://img.shields.io/badge/AWS_Lambdas-%23FF9900.svg?style=plastic&logo=awslambda&logoColor=white)
                ![Python](https://img.shields.io/badge/python-3670A0?style=plastic&logo=python&logoColor=ffdd54)
                ![Terraform](https://img.shields.io/badge/terraform-%235835CC.svg?style=plastic&logo=terraform&logoColor=white)
                ![Go](https://img.shields.io/badge/go-%2300ADD8.svg?style=plastic&logo=go&logoColor=white)
                ![Jira](https://img.shields.io/badge/jira-%230A0FFF.svg?style=plastic&logo=jira&logoColor=white)
                ![TensorFlow](https://img.shields.io/badge/TensorFlow-%23FF6F00.svg?style=plastic&logo=TensorFlow&logoColor=white)
                ![Pandas](https://img.shields.io/badge/pandas-%23150458.svg?style=plastic&logo=pandas&logoColor=white)
                ![PyTorch](https://img.shields.io/badge/PyTorch-%23EE4C2C.svg?style=plastic&logo=PyTorch&logoColor=white)
                ![mlflow](https://img.shields.io/badge/mlflow-%23d9ead3.svg?style=plastic&logo=numpy&logoColor=blue)

      - layout: left
        title: TechGenies / Leonardo247
        sub_title: Sr DevOps Engineer
        caption: April 2021 - April 2022
        description: | 
                - Skilled at working independently and collaboratively in a team environment.
                - Design new infrastructure on AWS EKS,
                - Infrastructure as Code using Terraform and Ansible.
                - Design security and scalability for development team to access resources.
                - Implement, Design and Review SOC 2 security compliance
                - DevSecOps practices using DAST and SAST software on GitLab Pipelines.
                - Design and monitoring SDLC and Infrastructure with Prometheus and Grafana and Datadog

      - layout: left
        title: Hexacta / Becton & Dickinson 
        sub_title: Senior Software Engineer
        caption: December 2020 - April 2021
        description: |
                - Observe, Analyze and Review Infrastructure and Application for cost effective solutions.
                - Design, Create and Implement 3-parties integrations with platform.
                - Monitoring, Design and Review DBs and transactional health during activity
                - Redesign DB schemas and operations through distributed events for better performance.
                - Create and Mantain Infrastructure cost, monitoring and solutions
                
      - layout: left
        title: Hexacta / Walkers
        sub_title: Principal Software Engineer
        caption: August 2019 - December 2020
        description: | 
                - Migration of old .NET 2 and ASP applications to .NET CORE and Web Technologies
                - Design, Create and Implement a new Standalone frontend architecture using angular
                - Split into Microservices and background jobs old .NET monolithic to be used for frontend
                - Redesign DB schemas and operations through event hubs
      
      - layout: left
        title: Hexacta / Coalfire
        sub_title: Senior Software Engineer
        caption: August 2016 - August 2019
        description: |
                - Backend API development with .NET and Java
                - Retrieve business values and requirements from stackeholders and customers
                - Performance testing and monitoring for backend applications performance
                - SQL and NOSQL such as mongodb for event system arcitecture.
                - Migration from Monolith to Microservice architecture using AWS EKS for orqestation

      - layout: left
        title: Hexacta / SanCor
        sub_title: .NET Software Engineer
        caption: August 2015 - April 2016
        description: | 
                - Refresh old intranet site to a public hosted domain web application for commerce
                - Design ServiceBus integration systems for high availability and reliability transaccional environment
                - Analyse and Optimize DB operations for low timing responses
      
      - layout: left
        title: Plus Sistemas S.A
        sub_title: .NET Software Engineer
        caption: May 2013 - July 2015
        description: | 
                - Troubleshot and resolved performance issues for databases and software.
                - Analyzed, evaluated and developed new web and database applications.
                - Software Engineer on .NET stack using MVC, WebAPI, SQL, Razor and web technologies.
                - Monitored database performance to keep workflows running smoothly.

      - layout: left
        title: Ministerio Salud Provincia de Buenos Aires
        sub_title: Database Administrator
        caption: September 2011 - March 2013
        description: | 
                - Administered, supported, and monitored databases by proactively resolving database issues and maintaining servers.
                - Developed and updated databases to handle customer data.
                - Worked with staff to develop and implement procedures to prevent data loss and maximize system availability.
                - Developed scripts and processes for data integration and maintenance.
                - Created and updated database designs and data models.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Universidad Nacional La Plata
        caption: 2009 - 2016
        sub_title: BSc Computer Science
        description: | 
            During my time at university I learnt most of my key skills that have I have taken through my career such as teamwork collaboration and working to tight deadlines on Agile environments.
            
            I owned a master in HA and Grid Scalable System Designs and Cloud Distributed Architectures.
            
            I had lot of experience at that time with Cloud and HA designs
  
  - title: Certification
    layout: list
    content:
      - layout: left
        title: AWS CloudPractitioner Certification
        caption: March, 2021
        sub_title: BSc Computer Science
        description: | 
            During my time at university I learnt most of my key skills that have I have taken through my career such as teamwork collaboration and working to tight deadlines on Agile environments.
            
            I owned a master in HA and Grid Scalable System Designs and Cloud Distributed Architectures.
            
            I had lot of experience at that time with Cloud and HA designs

# Footer
footer_show_references: true
references_title: Contact Me!

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
