# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Eliseo Gaston Lopez Ariza
title: Lead Site Reliability Engineer
# email: liseu.90@hotmail.com
# website: www.github.com/sproogen/resume-theme

darkmode: true

# plastic links
github_username:  eliseogaston
linkedin_username: eliseogaston
additional_links:
- title: Email me!
  icon: fa fa-envelope
  mailto: liseu.90@hotmail.com
#- title: Book Time with Me!
#  icon: fa fa-calendar
#  url: https://calendly.com/eliseogaston/book-me


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  I am a Lead Site Reliability Engineer with over 10 years of experience working with backend and cloud environments using technology stacks like .NET, Java and Go.
  I work with large and small teams to design, build, manage, monitor and architect micro-services and distributed HA systems that best meet the customer's requirements.
  
  My expertise in cloud infrastructure design architectures, strong skills in DevOps/DevSecOps, and years of experience in every part of the software development lifecycle help me make every decision professionally.
  
  I'm most interested in security, observability, and performances. Automating all of this is my fervent interest.
content:
  - title: Skills
    layout: text
    content: | 
        **Cloud Providers**:  AWS, Azure
            
        **Monitoring**:  Prometheus, Grafana, Loki, FluentD, FluentBit, Azure Application Insights
            
        **Observability**:  Datadog, New Relic, AWS CloudWatch

        **FinOps**: Terracost, Kubecost, CloudZero, Datadog, AWS Cost Management, Azure Cost Explorer
            
        **Containerization**:  Vagrant, Docker, COntainerD, LXC/LXD, BuildKit, Kaniko, Podman
        
        **Orquestation**:  Kubernetes, EKS, AKS, GKE, Docker Swarm, Docker Compose
        
        **Package Management**:  Helm, Kustomize
        
        **GitOps**:  ArgoCD, Tekton, Flux, Jenkins-x
        
        **VCS**:  Gitlab, Github, Azure DevOps
        
        **Infastructure as Code**:  Terraform, Pulumi, Crossplane, AWS CDK
        
        **Configuration as Code**:  Ansible, SaltStack
        
        **Programming Languaje**:  NET, Java, Golang
        
        **Databases**:  SQLs, MongoDB, Redis, Cassandra, DynamoDB
            
        **Methodologies**:  Git, Scrum, Kanban, SaFE

        **Shifts**: PagerDuty, AlertManager, Jira Incident Management, OpsGenie

  - title: Experience
    layout: list
    content:
      - layout: left
        title: GlobalLogic 
        sub_title: Lead Platform Engineer
        caption: September 2023 - Present (15 month)
        description: | 
              - Lead of Platform Engineer Team which standarize more than 30+ customers' teams
              - Coordinate and Lead Platform Team to provide Best Practices DevOps, DevSecOps, Cloud Architectures and Compliance as a standard
              - Design and architect micro-services and complex systems
              - Follow requirements,metrics and feedback from customers to get that improvement area retrofit.
              - Coordinated efficient large-scale software deployments and architecture for IoT, Healthcare and PCI environments.
              - Observe Infrastructure, Metrics and Budgets to give the customers the best cost efective solution for their business.  


      - layout: left
        title: Invenco by GVR
        sub_title: Senior Platform Engineer
        caption: December 2022 - September 2023 (10)
        description: |
              - Improve Dev experience
              - Implement Internal Developer Portal
              - Self provisioning Services and Infrastructure
              - Auto-heal systems
      
      - layout: left
        title: Marqeta
        sub_title: Lead DevOps Engineer
        caption: April 2022 - December 2022 (9 month)
        description: |
              - Implement CI/CD pipelines to automate provisioning of accounts
              - Implement OCTA worflows for users creation provition
              - Create, Mantain and Architect AWS LAMBDA for provitioning of accounts and services
              - Implement Observability and Monitoring on Serverless architecture
              - Reveal and Retrofit business needs for tracking business value. 
        
      - layout: left
        title: Leonardo247
        sub_title: Lead DevOps Engineer
        caption: April 2021 - April 2022 (12 month)
        description: | 
              - Skilled at working independently and collaboratively in a team environment.
              - Design new infrastructure on AWS EKS,
              - Infrastructure as Code using Terraform and Ansible.
              - Design security and scalability for development team to access resources.
              - Implement, Design and Review SOC 2 security compliance
              - DevSecOps practices using DAST and SAST software on GitLab Pipelines.
              - Design and monitoring SDLC and Infrastructure with Prometheus and Grafana and Datadog
                
      - layout: left
        title: Becton & Dickinson 
        sub_title: Senior DevOps Engineer
        caption: December 2019 - April 2021 (17 month)
        description: |
              - Observe, Analyze and Review Infrastructure and Application for cost effective solutions.
              - Design, Create and Implement 3-parties integrations with platform.
              - Monitoring, Design and Review DBs and transactional health during activity
              - Redesign DB schemas and operations through distributed events for better performance.
              - Create and Mantain Infrastructure cost, monitoring and solutions  
                
      - layout: left
        title: Walkers
        sub_title: Lead Software Engineer
        caption: August 2018 - December 2019 (16 month)
        description: | 
              - Migration of old .NET 2 and ASP applications to .NET CORE and Web Technologies
              - Design, Create and Implement a new Standalone frontend architecture using angular
              - Split into Microservices and background jobs old .NET monolithic to be used for frontend
              - Redesign DB schemas and operations through event hubs  
      
      - layout: left
        title: Coalfire
        sub_title: Senior Software Engineer
        caption: August 2016 - August 2018 (36 month)
        description: |
              - Backend API development with .NET and Java
              - Retrieve business values and requirements from stackeholders and customers
              - Performance testing and monitoring for backend applications performance
              - SQL and NOSQL such as mongodb for event system arcitecture.
              - Migration from Monolith to Microservice architecture using AWS EKS for orqestation  

      - layout: left
        title: SanCor
        sub_title: .NET Software Engineer
        caption: August 2015 - April 2016 (9 month)
        description: | 
              - Refresh old intranet site to a public hosted domain web application for commerce
              - Design ServiceBus integration systems for high availability and reliability transaccional environment
              - Analyse and Optimize DB operations for low timing responses  
      
      - layout: left
        title: Plus Sistemas S.A
        sub_title: .NET Software Engineer
        caption: May 2013 - July 2015 (26 month)
        description: | 
              - Troubleshot and resolved performance issues for databases and software.
              - Analyzed, evaluated and developed new web and database applications.
              - Software Engineer on .NET stack using MVC, WebAPI, SQL, Razor and web technologies.
              - Monitored database performance to keep workflows running smoothly.  

      - layout: left
        title: Ministerio Salud Provincia de Buenos Aires
        sub_title: Database Administrator
        caption: September 2011 - March 2013
        description: | 
              - Administered, supported, and monitored databases by proactively resolving database issues and maintaining servers.
              - Developed and updated databases to handle customer data.
              - Worked with staff to develop and implement procedures to prevent data loss and maximize system availability.
              - Developed scripts and processes for data integration and maintenance.
              - Created and updated database designs and data models. 

  
  - title: Education
    layout: list
    content:
      - layout: left
        title: Universidad Nacional La Plata
        caption: 2009 - 2016
        sub_title: BSc Computer Science
        description: | 
            During my time at university I learnt most of my key skills that have I have taken through my career such as teamwork collaboration and working to tight deadlines on Agile environments.
            
            I owned a master in HA and Grid Scalable System Designs and Cloud Distributed Architectures.
            
            I had lot of experience at that time with Cloud and HA designs  

# Footer
footer_show_references: true
references_title: Contact Me!

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
